"use client";
import React, { createContext, useContext, useState } from "react";
import { fetchContentStrings } from "./api";

export type Language = "en" | "ny";

type TranslationMap = Record<string, string>;

const translations: Record<Language, TranslationMap> = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.profile": "Financial Profile",
    "nav.institutions": "Check Eligibility",
    "nav.compare": "Compare Lenders",
    "nav.loans": "Active Loans",
    "nav.calculator": "Calculator",
    "nav.back": "Back",
    "nav.logout": "Sign Out",
    "theme.light": "Light Mode",
    "theme.dark": "Dark Mode",
    "prefs.label": "Display preferences",
    "prefs.language": "Language",
    "action.apply": "Compare Lenders",
    "home.welcome": "Welcome",
    "home.noBank": "No Bank",
    "home.completeProfile": "Complete your financial profile",
    "home.unlockMsg": "to unlock loan eligibility checks and applications.",
    "home.setupLink": "Set up profile",
    "home.salary": "Monthly Salary",
    "home.dti": "DTI Ratio",
    "home.activePrincipal": "Active Principal",
    "home.risk": "Risk Level",
    "home.netIncome": "Net income",
    "home.threshold": "Threshold: 33%",
    "home.remainingBalance": "Remaining balance",
    "home.riskCategory": "Risk Category",
    "home.high": "High",
    "home.moderate": "Moderate",
    "home.low": "Low",
    "home.debtAnalysis": "Debt-to-Income Analysis",
    "home.creditUtilization": "Credit Utilization",
    "home.utilizing": "Utilizing {percent}% of estimated borrowing capacity",
    "home.smartInsights": "Smart Insights",
    "home.quickActions": "Quick Actions",
    "home.recentApplications": "Recent Applications",
    "home.announcements": "Announcements",
    "home.noAnnouncements": "No announcements available",
    "home.recentAnnouncements": "Recent Announcements",
    "home.viewAllAnnouncements": "View all announcements",
    "home.loadingAnnouncements": "Loading announcements...",
    "home.viewAll": "View All",
    "home.date": "Date",
    "home.amount": "Amount",
    "home.duration": "Duration",
    "home.riskScore": "Risk Score",
    "home.status": "Status",
    "home.months": "months",
    "home.insightHighRisk": "High Risk: DTI exceeds 33%. You may face rejection for new loans.",
    "home.insightModerateRisk": "Moderate Risk: DTI between 20-33%. Manageable but monitor closely.",
    "home.insightLowRisk": "Low Risk: DTI under 20%. You have healthy borrowing capacity.",
    "home.insightCapacity": "You have available capacity for additional borrowing.",
    "home.actionCheckTitle": "Check Eligibility",
    "home.actionCheckDesc": "See which institutions you qualify for",
    "home.actionCompareTitle": "Compare Lenders",
    "home.actionCompareDesc": "Side-by-side bank comparison",
    "home.actionRecordTitle": "Record Manual Loan",
    "home.actionRecordDesc": "Track your existing loans",
    "home.actionLoansTitle": "Active Loans",
    "home.actionLoansDesc": "View amortization schedules",
    "home.actionProfileTitle": "Update Profile",
    "home.actionProfileDesc": "Edit financial information",
    "eligibility.title": "Loan Eligibility Comparison",
    "eligibility.subtitle":
      "Discover where you are likely to qualify and compare terms across Malawian lenders.",
    "eligibility.profileRequired": "You need to complete your",
    "eligibility.profileLink": "financial profile",
    "eligibility.profileRequiredEnd": "before generating a comparison.",
    "eligibility.parameters": "Loan Details",
    "eligibility.amount": "Requested Amount (MK)",
    "eligibility.period": "Repayment Period",
    "eligibility.periodHelp": "Choose your comfortable repayment timeframe",
    "eligibility.months": "months",
    "eligibility.years": "years",
    "eligibility.loading": "Scanning lenders...",
    "eligibility.check": "Check Eligibility",
    "eligibility.selectInstitution": "Select Institution",
    "eligibility.chooseInstitution": "Choose an institution",
    "eligibility.compareAllLendersInfo": "All active lenders are selected by default. Uncheck ones you do not want to include.",
    "eligibility.compare": "Compare Eligible Lenders",
    "eligibility.summarySalary": "Based on your net salary of",
    "eligibility.summaryDeductions": "and existing deductions of",
    "eligibility.topMatches": "Top Eligible Matches",
    "eligibility.noMatches":
      "No lenders matched your requested amount and profile. Check the ineligible list below to see why.",
    "eligibility.bestMatch": "Best Match",
    "eligibility.interestRate": "Interest Rate",
    "eligibility.processingFee": "Processing Fee",
    "eligibility.monthlyPayment": "Est. Monthly Payment",
    "eligibility.maxCapacity": "Max Capacity",
    "eligibility.prequalified": "Pre-qualified",
    "eligibility.visitBranch": "Visit any {institution} branch to proceed.",
    "eligibility.otherInstitutions": "Other Institutions (Not Eligible)",
    "eligibility.availableLenders": "Available Lenders on DLEM",
    "eligibility.offers": "Offers {rate}% interest rates up to {months} months.",
    "check.title": "Check Eligibility",
    "check.subtitle": "Choose one lender and answer the guided questions before checking.",
    "check.loading": "Loading live institution data...",
    "check.emptyInstitutions": "No institutions are currently available. Please check back soon.",
    "check.continue": "Continue",
    "check.refresh": "Refresh",
    "check.selectInstitutionStep": "Select Institution",
    "check.subselectStep": "Select Product",
    "check.additionalDetailsStep": "Additional Details",
    "check.resultsStep": "Eligibility Results",
    "check.fincaProductTitle": "Select a FINCA Loan Product",
    "check.fincaProductDescription": "Choose the loan product you would like to check your eligibility for.",
    "check.fincaEmptyProducts": "No FINCA loan products are currently available. Please check back soon.",
    "check.fincaValidation": "Please select a loan product to continue.",
    "check.fincaMoreSoon": "More FINCA loan products will be added soon.",
    "check.comingSoon": "Coming Soon",
    "check.backToInstitutions": "Back",
    "check.productFallbackDescription": "Eligibility criteria are managed by the lender.",
    "auth.back": "Back",
    "auth.loginTitle": "Welcome Back",
    "auth.loginSubtitle": "Sign in to access your dashboard",
    "auth.email": "Email Address",
    "auth.emailPlaceholder": "your@email.com",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Your password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.signIn": "Sign In",
    "auth.signingIn": "Signing in...",
    "auth.newCustomer": "New customer?",
    "auth.createAccount": "Create an Account",
    "auth.invalidLogin": "Invalid email or password. Please try again.",
    "auth.networkError": "Network error. Please try again.",
    "auth.registerTitle": "Create Account",
    "auth.registerSubtitle": "Join thousands of Malawians managing loans digitally",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "e.g. John Banda",
    "auth.nationalId": "National ID",
    "auth.nationalIdPlaceholder": "MW-XXXXXXXXXX",
    "auth.employeeNumber": "Employee / Member ID",
    "auth.employeeNumberPlaceholder": "e.g. CS-2024-XXXX",
    "auth.phone": "Phone Number",
    "auth.phonePlaceholder": "+265 XXXXXXXX",
    "auth.emailRegisterPlaceholder": "yourname@example.com",
    "auth.emailHelp": "Your login details and notifications will be sent here.",
    "auth.validEmail": "Valid email",
    "auth.invalidEmail": "Enter a valid email address (e.g. john@example.com)",
    "auth.passwordMin": "Min. 8 characters",
    "auth.passwordTooShort": "At least 8 characters required",
    "auth.confirmPassword": "Confirm Password",
    "auth.confirmPasswordPlaceholder": "Repeat password",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordsMatch": "Passwords match",
    "auth.creatingAccount": "Creating Account...",
    "auth.createAccountButton": "Create Account",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.checkEmailTitle": "Check Your Email",
    "auth.checkEmailSubtitle": "We sent a 6-digit verification code to",
    "auth.enterAllDigits": "Please enter all 6 digits.",
    "auth.invalidOtp": "Invalid or expired code. Please try again.",
    "auth.verifyNetworkError": "Network error - could not verify your code. Please try again.",
    "auth.resendError": "Could not resend code. Please try again.",
    "auth.registrationFailed": "Registration failed. Please try again.",
    "auth.registrationNetworkError": "Network error - could not reach the server. Please check your connection.",
    "auth.developmentCode": "Development code",
    "auth.verifying": "Verifying...",
    "auth.verifyCreate": "Verify & Create Account",
    "auth.didNotReceive": "Didn't receive a code?",
    "auth.resendIn": "Resend in {seconds}s",
    "auth.resendCode": "Resend code",
    "auth.hidePassword": "Hide password",
    "auth.showPassword": "Show password",
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.save": "Save",
    "calc.title": "Loan Calculator",
    "calc.subtitle": "Caps, rates, and terms come from the live institution criteria API.",
    "calc.loading": "Loading calculator...",
    "calc.institution": "Institution",
    "calc.loanProduct": "Loan Product",
    "calc.loanAmount": "Loan Amount",
    "calc.annualInterest": "Annual Interest Rate",
    "calc.fixed": "{rate}% fixed",
    "calc.repaymentPeriod": "Repayment Period",
    "calc.monthlyInstallment": "Monthly Installment",
    "calc.totalRepayable": "Total Repayable",
    "calc.dtiCap": "DTI Cap",
    "calc.processingFee": "Processing Fee",
    "loans.title": "My Loans",
    "loans.subtitle": "Track your active loans",
    "loans.loading": "Loading loans...",
    "loans.record": "Record Manual Loan",
    "loans.active": "Active Loans",
    "loans.monthly": "Monthly",
    "loans.paidMonths": "Paid Months",
    "loans.remaining": "Remaining",
    "loans.startDate": "Start Date",
    "loans.progress": "Repayment Progress",
    "loans.viewSchedule": "View Schedule",
    "loans.manualRecord": "Manual Record",
    "loans.removeConfirm": "Are you sure you want to remove this loan? This will also update your monthly debt capacity.",
    "loans.remove": "Remove loan",
    "loans.markPaidConfirm": "Mark this whole loan as fully paid?\n\nRemaining balance: MK {balance}",
    "loans.completeError": "Could not complete loan",
    "loans.processing": "Processing...",
    "loans.markFullyPaid": "Mark Loan as Fully Paid",
    "profile.title": "Financial Profile",
    "profile.subtitle": "This information is used to calculate your loan eligibility and risk score across Malawian lenders.",
    "profile.employmentDetails": "Employment Details",
    "profile.employer": "Employer / Organization",
    "profile.employerPlaceholder": "e.g. Ministry of Health, Airtel, etc.",
    "profile.employmentCategory": "Employment Category",
    "profile.selectCategory": "Select Category",
    "profile.civilServant": "Civil Servant (Government)",
    "profile.privateSector": "Private Sector",
    "profile.selfEmployed": "Self-Employed / Business Owner",
    "profile.categoryHelp": "This determines which lenders and multipliers you are eligible for.",
    "profile.netSalary": "Net Monthly Salary (MK)",
    "profile.salaryHelp": "Enter your monthly take-home pay in Malawian Kwacha (after all standard tax deductions).",
    "profile.serviceLength": "Length of Service / Time in Business",
    "profile.monthsLabel": "(months)",
    "profile.serviceHelp": "Enter the total number of months you have been employed or in business. Used by SACCO and other lenders to verify minimum service requirements.",
    "profile.personalFinancial": "Personal & Financial Details",
    "profile.primaryBank": "Primary Salary Bank",
    "profile.unbanked": "Unbanked / Other",
    "profile.bankHelp": "Where your salary is deposited. Leave blank if unbanked.",
    "profile.age": "Age",
    "profile.housingStatus": "Housing Status",
    "profile.selectStatus": "Select status",
    "profile.owner": "Property Owner",
    "profile.tenant": "Tenant / Renting",
    "profile.family": "Living with Family",
    "profile.existingRepayments": "Monthly Existing Loan Repayments (MK)",
    "profile.existingHelp": "Total monthly repayments on all current loans. Affects your DTI ratio.",
    "profile.dependants": "Number of Dependants",
    "profile.dependantsHelp": "Total number of people financially dependent on you (children, spouse, parents, etc.).",
    "profile.bankingYears": "Years with Current Bank",
    "profile.saved": "Profile saved successfully!",
    "profile.saveFailed": "Save failed.",
    "profile.saving": "Saving...",
    "profile.saveProfile": "Save Profile",
    "landing.nav.features": "Features",
    "landing.nav.how": "How It Works",
    "landing.nav.partners": "Partners",
    "landing.hero.title": "Smart Loans,",
    "landing.hero.highlight": "Trusted Advisor.",
    "landing.hero.subtitle": "Loan eligibility check | Track repayment | lender comparison",
    "landing.hero.getStarted": "Get Started",
    "landing.hero.signIn": "Sign In",
    "landing.stats.institutions": "Multi-Institution",
    "landing.stats.supported": "Supported",
    "landing.stats.time": "< 5 min",
    "landing.stats.eligibility": "Eligibility Check",
    "landing.stats.digital": "100%",
    "landing.stats.process": "Digital Process",
    "landing.features.title": "Everything You Need, Digitally",
    "landing.features.subtitle": "No queues. No paperwork. No branch visits required.",
    "landing.feature.instantTitle": "Instant Eligibility Check",
    "landing.feature.instantDesc": "Get an automated risk score and eligibility verdict in under 2 minutes based on your financial profile.",
    "landing.feature.applyTitle": "Apply From Anywhere",
    "landing.feature.applyDesc": "Submit your personal loan application from your phone or computer - no branch visit required.",
    "landing.feature.simulatorTitle": "Loan Repayment Simulator",
    "landing.feature.simulatorDesc": "Calculate your monthly installments, total cost, and full amortization schedule before you commit.",
    "landing.feature.statusTitle": "Real-Time Status Tracking",
    "landing.feature.statusDesc": "Track your application status from submission through credit officer review to final decision.",
    "landing.feature.dashboardTitle": "Active Loan Dashboard",
    "landing.feature.dashboardDesc": "Monitor outstanding balance, paid months, and upcoming payments from your personal dashboard.",
    "landing.feature.secureTitle": "Secure & Private",
    "landing.feature.secureDesc": "Your financial data is encrypted and protected. Only you and your bank officer can access your profile.",
    "landing.how.title": "How It Works",
    "landing.step.accountTitle": "Create Account",
    "landing.step.accountDesc": "Register with your National ID, phone number, and select your bank in under 2 minutes.",
    "landing.step.profileTitle": "Set Financial Profile",
    "landing.step.profileDesc": "Enter your employment details, monthly salary, housing, and existing loan obligations.",
    "landing.step.checkTitle": "Check Eligibility",
    "landing.step.checkDesc": "Our engine runs automated risk scoring using real banking criteria and gives you instant feedback.",
    "landing.step.trackTitle": "Loan Tracking",
    "landing.step.trackDesc": "Monitor your active loan balance, repayment progress, paid months, and upcoming payment schedule from your dashboard.",
    "landing.partners.title": "Our Institution Partners",
    "landing.partner.fdh": "Personal & salary loans - civil servants & private sector",
    "landing.partner.sacco": "Member loans - competitive rates - Malawi Police SACCO",
    "landing.partner.finca": "Group / Village Bank loans - business owners",
    "landing.cta.title": "Ready to Apply?",
    "landing.cta.subtitle": "Join thousands of Malawians easing their banking experience digitally.",
    "landing.cta.button": "Create Free Account",
    "landing.footer": "Your trusted partner in financial inclusion",
    "common.openNavigation": "Open navigation menu",
    "common.notifications": "Notifications",
    "common.loadingContent": "Loading content...",
    "admin.title": "DLEM Admin",
    "admin.verifying": "Verifying admin session...",
    "admin.superAdministrator": "Super Administrator",
    "admin.contentAdministrator": "Content Administrator",
    "admin.superAdmin": "Super Admin",
    "admin.contentAdmin": "Content Admin",
    "admin.nav.dashboard": "Dashboard",
    "admin.nav.institutions": "Institutions",
    "admin.nav.users": "Users",
    "admin.nav.eligibility": "Eligibility Monitor",
    "admin.nav.announcements": "Announcements",
    "admin.nav.admins": "Admin Accounts",
  },
  ny: {
    "nav.dashboard": "Zoyang'anira",
    "nav.profile": "Mbiri Yachuma",
    "nav.institutions": "Onani Mwayi",
    "nav.compare": "Yerekezerani Obwereketsa",
    "nav.loans": "Ngongole Zanga",
    "nav.calculator": "Chowerengera",
    "nav.back": "Back",
    "nav.logout": "Tulukani",
    "theme.light": "Mawonekedwe Owoneka",
    "theme.dark": "Mawonekedwe Amdima",
    "prefs.label": "Display preferences",
    "prefs.language": "Language",
    "action.apply": "Yerekezerani Obwereketsa",
    "home.welcome": "Takulandirani",
    "home.noBank": "Palibe Banki",
    "home.completeProfile": "Malizitsani mbiri yanu ya zachuma",
    "home.unlockMsg": "kuti mutsegule kuyang'ana mwayi wa ngongole.",
    "home.setupLink": "Konzani mbiri",
    "home.salary": "Malipiro Apamwezi",
    "home.dti": "Chiwerengero cha Ngongole",
    "home.activePrincipal": "Ngongole Yotsala",
    "home.risk": "Mulingo wa Chiwopsezo",
    "home.netIncome": "Net income",
    "home.threshold": "Threshold: 33%",
    "home.remainingBalance": "Remaining balance",
    "home.riskCategory": "Risk Category",
    "home.high": "High",
    "home.moderate": "Moderate",
    "home.low": "Low",
    "home.debtAnalysis": "Debt-to-Income Analysis",
    "home.creditUtilization": "Credit Utilization",
    "home.utilizing": "Utilizing {percent}% of estimated borrowing capacity",
    "home.smartInsights": "Smart Insights",
    "home.quickActions": "Quick Actions",
    "home.recentApplications": "Recent Applications",
    "home.announcements": "Zilengezo",
    "home.noAnnouncements": "Palibe zilengezo",
    "home.recentAnnouncements": "Zilengezo Zaposachedwa",
    "home.viewAllAnnouncements": "Onani zilengezo zonse",
    "home.loadingAnnouncements": "Zilengezo zikubwera...",
    "home.viewAll": "View All",
    "home.date": "Date",
    "home.amount": "Amount",
    "home.duration": "Duration",
    "home.riskScore": "Risk Score",
    "home.status": "Status",
    "home.months": "months",
    "home.insightHighRisk": "High Risk: DTI exceeds 33%. You may face rejection for new loans.",
    "home.insightModerateRisk": "Moderate Risk: DTI between 20-33%. Manageable but monitor closely.",
    "home.insightLowRisk": "Low Risk: DTI under 20%. You have healthy borrowing capacity.",
    "home.insightCapacity": "You have available capacity for additional borrowing.",
    "home.actionCheckTitle": "Check Eligibility",
    "home.actionCheckDesc": "See which institutions you qualify for",
    "home.actionCompareTitle": "Compare Lenders",
    "home.actionCompareDesc": "Side-by-side bank comparison",
    "home.actionRecordTitle": "Record Manual Loan",
    "home.actionRecordDesc": "Track your existing loans",
    "home.actionLoansTitle": "Active Loans",
    "home.actionLoansDesc": "View amortization schedules",
    "home.actionProfileTitle": "Update Profile",
    "home.actionProfileDesc": "Edit financial information",
    "eligibility.title": "Kuyerekeza Mwayi wa Ngongole",
    "eligibility.subtitle":
      "Onani komwe mungavomerezedwe ndipo yerekezerani mawu a obwereketsa ku Malawi.",
    "eligibility.profileRequired": "Muyenera kumaliza",
    "eligibility.profileLink": "mbiri yanu ya zachuma",
    "eligibility.profileRequiredEnd": "musanayambe kuyerekeza.",
    "eligibility.parameters": "Zambiri za Ngongole",
    "eligibility.amount": "Ndalama Zomwe Mukufuna (MK)",
    "eligibility.period": "Nthawi Yobweza",
    "eligibility.periodHelp": "Sankhani nthawi yobweza yomwe ingakuyenereni",
    "eligibility.months": "miyezi",
    "eligibility.years": "zaka",
    "eligibility.loading": "Tikuyang'ana obwereketsa...",
    "eligibility.check": "Onani Mwayi",
    "eligibility.compareAllLendersInfo": "Obwereketsa onse omwe alipo akusankhidwa mwachisawawa. Chotsani amene mukufuna osasinthidwa.",
    "eligibility.compare": "Yerekezerani Obwereketsa",
    "eligibility.selectInstitution": "Sankhani Obwereketsa",
    "eligibility.chooseInstitution": "Sankhani obwereketsa",
    "eligibility.summarySalary": "Zatengera malipiro anu a neti a",
    "eligibility.summaryDeductions": "ndi zobweza zina za",
    "eligibility.topMatches": "Obwereketsa Oyenera Kwambiri",
    "eligibility.noMatches":
      "Palibe wobwereketsa amene wagwirizana ndi ndalama zomwe mukufuna. Onani mndandanda wapansi kuti mudziwe chifukwa.",
    "eligibility.bestMatch": "Woyenera Kwambiri",
    "eligibility.interestRate": "Chiwongola Dzanja",
    "eligibility.processingFee": "Ndalama Zokonza",
    "eligibility.monthlyPayment": "Zobweza Pamwezi",
    "eligibility.maxCapacity": "Malire a Ngongole",
    "eligibility.prequalified": "Mungayenerere",
    "eligibility.visitBranch": "Pitani ku nthambi ya {institution} kuti mupitirize.",
    "eligibility.otherInstitutions": "Ena Osayenerera",
    "eligibility.availableLenders": "Obwereketsa Omwe Alipo pa DLEM",
    "eligibility.offers":
      "Amapereka chiwongola dzanja cha {rate}% mpaka miyezi {months}.",
    "check.title": "Onani Mwayi",
    "check.subtitle": "Sankhani wobwereketsa mmodzi ndipo yankhani mafunso musanayambe kuyang'ana.",
    "check.loading": "Loading live institution data...",
    "check.emptyInstitutions": "No institutions are currently available. Please check back soon.",
    "check.continue": "Continue",
    "check.refresh": "Refresh",
    "check.selectInstitutionStep": "Select Institution",
    "check.subselectStep": "Select Product",
    "check.additionalDetailsStep": "Additional Details",
    "check.resultsStep": "Eligibility Results",
    "check.fincaProductTitle": "Select a FINCA Loan Product",
    "check.fincaProductDescription": "Choose the loan product you would like to check your eligibility for.",
    "check.fincaEmptyProducts": "No FINCA loan products are currently available. Please check back soon.",
    "check.fincaValidation": "Please select a loan product to continue.",
    "check.fincaMoreSoon": "More FINCA loan products will be added soon.",
    "check.comingSoon": "Coming Soon",
    "check.backToInstitutions": "Back",
    "check.productFallbackDescription": "Eligibility criteria are managed by the lender.",
    "auth.back": "Back",
    "auth.loginTitle": "Welcome Back",
    "auth.loginSubtitle": "Sign in to access your dashboard",
    "auth.email": "Email Address",
    "auth.emailPlaceholder": "your@email.com",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Your password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.signIn": "Sign In",
    "auth.signingIn": "Signing in...",
    "auth.newCustomer": "New customer?",
    "auth.createAccount": "Create an Account",
    "auth.invalidLogin": "Invalid email or password. Please try again.",
    "auth.networkError": "Network error. Please try again.",
    "auth.registerTitle": "Create Account",
    "auth.registerSubtitle": "Join thousands of Malawians managing loans digitally",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "e.g. John Banda",
    "auth.nationalId": "National ID",
    "auth.nationalIdPlaceholder": "MW-XXXXXXXXXX",
    "auth.employeeNumber": "Employee / Member ID",
    "auth.employeeNumberPlaceholder": "e.g. CS-2024-XXXX",
    "auth.phone": "Phone Number",
    "auth.phonePlaceholder": "+265 XXXXXXXX",
    "auth.emailRegisterPlaceholder": "yourname@example.com",
    "auth.emailHelp": "Your login details and notifications will be sent here.",
    "auth.validEmail": "Valid email",
    "auth.invalidEmail": "Enter a valid email address (e.g. john@example.com)",
    "auth.passwordMin": "Min. 8 characters",
    "auth.passwordTooShort": "At least 8 characters required",
    "auth.confirmPassword": "Confirm Password",
    "auth.confirmPasswordPlaceholder": "Repeat password",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordsMatch": "Passwords match",
    "auth.creatingAccount": "Creating Account...",
    "auth.createAccountButton": "Create Account",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.checkEmailTitle": "Check Your Email",
    "auth.checkEmailSubtitle": "We sent a 6-digit verification code to",
    "auth.enterAllDigits": "Please enter all 6 digits.",
    "auth.invalidOtp": "Invalid or expired code. Please try again.",
    "auth.verifyNetworkError": "Network error - could not verify your code. Please try again.",
    "auth.resendError": "Could not resend code. Please try again.",
    "auth.registrationFailed": "Registration failed. Please try again.",
    "auth.registrationNetworkError": "Network error - could not reach the server. Please check your connection.",
    "auth.developmentCode": "Development code",
    "auth.verifying": "Verifying...",
    "auth.verifyCreate": "Verify & Create Account",
    "auth.didNotReceive": "Didn't receive a code?",
    "auth.resendIn": "Resend in {seconds}s",
    "auth.resendCode": "Resend code",
    "auth.hidePassword": "Hide password",
    "auth.showPassword": "Show password",
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.save": "Save",
    "calc.title": "Loan Calculator",
    "calc.subtitle": "Caps, rates, and terms come from the live institution criteria API.",
    "calc.loading": "Loading calculator...",
    "calc.institution": "Institution",
    "calc.loanProduct": "Loan Product",
    "calc.loanAmount": "Loan Amount",
    "calc.annualInterest": "Annual Interest Rate",
    "calc.fixed": "{rate}% fixed",
    "calc.repaymentPeriod": "Repayment Period",
    "calc.monthlyInstallment": "Monthly Installment",
    "calc.totalRepayable": "Total Repayable",
    "calc.dtiCap": "DTI Cap",
    "calc.processingFee": "Processing Fee",
    "loans.title": "My Loans",
    "loans.subtitle": "Track your active loans",
    "loans.loading": "Loading loans...",
    "loans.record": "Record Manual Loan",
    "loans.active": "Active Loans",
    "loans.monthly": "Monthly",
    "loans.paidMonths": "Paid Months",
    "loans.remaining": "Remaining",
    "loans.startDate": "Start Date",
    "loans.progress": "Repayment Progress",
    "loans.viewSchedule": "View Schedule",
    "loans.manualRecord": "Manual Record",
    "loans.removeConfirm": "Are you sure you want to remove this loan? This will also update your monthly debt capacity.",
    "loans.remove": "Remove loan",
    "loans.markPaidConfirm": "Mark this whole loan as fully paid?\n\nRemaining balance: MK {balance}",
    "loans.completeError": "Could not complete loan",
    "loans.processing": "Processing...",
    "loans.markFullyPaid": "Mark Loan as Fully Paid",
    "profile.title": "Financial Profile",
    "profile.subtitle": "This information is used to calculate your loan eligibility and risk score across Malawian lenders.",
    "profile.employmentDetails": "Employment Details",
    "profile.employer": "Employer / Organization",
    "profile.employerPlaceholder": "e.g. Ministry of Health, Airtel, etc.",
    "profile.employmentCategory": "Employment Category",
    "profile.selectCategory": "Select Category",
    "profile.civilServant": "Civil Servant (Government)",
    "profile.privateSector": "Private Sector",
    "profile.selfEmployed": "Self-Employed / Business Owner",
    "profile.categoryHelp": "This determines which lenders and multipliers you are eligible for.",
    "profile.netSalary": "Net Monthly Salary (MK)",
    "profile.salaryHelp": "Enter your monthly take-home pay in Malawian Kwacha (after all standard tax deductions).",
    "profile.serviceLength": "Length of Service / Time in Business",
    "profile.monthsLabel": "(months)",
    "profile.serviceHelp": "Enter the total number of months you have been employed or in business. Used by SACCO and other lenders to verify minimum service requirements.",
    "profile.personalFinancial": "Personal & Financial Details",
    "profile.primaryBank": "Primary Salary Bank",
    "profile.unbanked": "Unbanked / Other",
    "profile.bankHelp": "Where your salary is deposited. Leave blank if unbanked.",
    "profile.age": "Age",
    "profile.housingStatus": "Housing Status",
    "profile.selectStatus": "Select status",
    "profile.owner": "Property Owner",
    "profile.tenant": "Tenant / Renting",
    "profile.family": "Living with Family",
    "profile.existingRepayments": "Monthly Existing Loan Repayments (MK)",
    "profile.existingHelp": "Total monthly repayments on all current loans. Affects your DTI ratio.",
    "profile.dependants": "Number of Dependants",
    "profile.dependantsHelp": "Total number of people financially dependent on you (children, spouse, parents, etc.).",
    "profile.bankingYears": "Years with Current Bank",
    "profile.saved": "Profile saved successfully!",
    "profile.saveFailed": "Save failed.",
    "profile.saving": "Saving...",
    "profile.saveProfile": "Save Profile",
    "landing.nav.features": "Zinthu Zofunika",
    "landing.nav.how": "Mmene Zimagwirira Ntchito",
    "landing.nav.partners": "Othandizana Nawo",
    "landing.hero.title": "Ngongole Zanzeru,",
    "landing.hero.highlight": "Mlangizi Wodalirika.",
    "landing.hero.subtitle": "Onani mwayi wa ngongole | Tsatirani kubweza | Yerekezerani obwereketsa",
    "landing.hero.getStarted": "Yambirani",
    "landing.hero.signIn": "Lowani",
    "landing.stats.institutions": "Mabungwe Ambiri",
    "landing.stats.supported": "Amathandizidwa",
    "landing.stats.time": "< mphindi 5",
    "landing.stats.eligibility": "Kuyang'ana Mwayi",
    "landing.stats.digital": "100%",
    "landing.stats.process": "Njira ya Pa Intaneti",
    "landing.features.title": "Zonse Zomwe Mukufuna, Pa Intaneti",
    "landing.features.subtitle": "Palibe mizere. Palibe mapepala. Palibe kufunika kopita kunthambi.",
    "landing.feature.instantTitle": "Kuyang'ana Mwayi Mwamsanga",
    "landing.feature.instantDesc": "Pezani mulingo wa chiwopsezo ndi zotsatira za mwayi wa ngongole pasanathe mphindi ziwiri pogwiritsa ntchito mbiri yanu ya zachuma.",
    "landing.feature.applyTitle": "Pemphani Kulikonse",
    "landing.feature.applyDesc": "Tumizani pempho lanu la ngongole pa foni kapena kompyuta popanda kupita kunthambi.",
    "landing.feature.simulatorTitle": "Chowerengera Kubweza Ngongole",
    "landing.feature.simulatorDesc": "Werengerani zobweza pamwezi, ndalama zonse, ndi ndondomeko yonse yobweza musanavomereze.",
    "landing.feature.statusTitle": "Kutsatira Mkhalidwe Nthawi Yeniyeni",
    "landing.feature.statusDesc": "Tsatirani pempho lanu kuyambira potumiza mpaka kuunika ndi chisankho chomaliza.",
    "landing.feature.dashboardTitle": "Dashboard ya Ngongole Zomwe Zikuyenda",
    "landing.feature.dashboardDesc": "Onani ndalama zotsala, miyezi yomwe yalipidwa, ndi zolipira zikubwera pa dashboard yanu.",
    "landing.feature.secureTitle": "Zotetezeka Komanso Zachinsinsi",
    "landing.feature.secureDesc": "Zambiri zanu za zachuma zimatetezedwa. Inu ndi wogwira ntchito ku banki yokha mungathe kuziwona.",
    "landing.how.title": "Mmene Zimagwirira Ntchito",
    "landing.step.accountTitle": "Pangani Akaunti",
    "landing.step.accountDesc": "Lembetsani ndi National ID yanu, nambala ya foni, ndi kusankha banki pasanathe mphindi ziwiri.",
    "landing.step.profileTitle": "Konzani Mbiri ya Zachuma",
    "landing.step.profileDesc": "Lowetsani ntchito yanu, malipiro apamwezi, malo okhala, ndi ngongole zomwe muli nazo.",
    "landing.step.checkTitle": "Onani Mwayi",
    "landing.step.checkDesc": "Makina athu amawerengera chiwopsezo pogwiritsa ntchito malamulo a mabanki ndipo amakupatsani yankho nthawi yomweyo.",
    "landing.step.trackTitle": "Tsatirani Ngongole",
    "landing.step.trackDesc": "Onani ngongole yotsala, momwe mukubwezera, miyezi yolipidwa, ndi ndondomeko ya zolipira zikubwera.",
    "landing.partners.title": "Mabungwe Othandizana Nafe",
    "landing.partner.fdh": "Ngongole za munthu payekha ndi za malipiro - ogwira boma ndi mabungwe apadera",
    "landing.partner.sacco": "Ngongole za mamembala - chiwongola dzanja chabwino - Malawi Police SACCO",
    "landing.partner.finca": "Ngongole za magulu / Village Bank - eni mabizinesi",
    "landing.cta.title": "Mwakonzeka Kupempha?",
    "landing.cta.subtitle": "Lowani nawo anthu ambiri ku Malawi omwe akugwiritsa ntchito njira za digito pa zachuma.",
    "landing.cta.button": "Pangani Akaunti Yaulere",
    "landing.footer": "Mnzanu wodalirika pa kupititsa patsogolo zachuma",
    "common.openNavigation": "Tsegulani menyu",
    "common.notifications": "Zidziwitso",
    "common.loadingContent": "Zikubwera...",
    "admin.title": "DLEM Admin",
    "admin.verifying": "Tikutsimikizira admin...",
    "admin.superAdministrator": "Woyang'anira Wamkulu",
    "admin.contentAdministrator": "Woyang'anira Zolemba",
    "admin.superAdmin": "Admin Wamkulu",
    "admin.contentAdmin": "Admin wa Zolemba",
    "admin.nav.dashboard": "Dashboard",
    "admin.nav.institutions": "Mabungwe",
    "admin.nav.users": "Ogwiritsa Ntchito",
    "admin.nav.eligibility": "Kuyang'anira Mwayi",
    "admin.nav.announcements": "Zilengezo",
    "admin.nav.admins": "Maakaunti a Admin",
  },
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: "en",
  setLanguage: () => {},
  t: key => translations.en[key] || key,
});

export const LanguageProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [language, setLanguageState] = useState<Language>("en");
  const [liveStrings, setLiveStrings] = useState<Record<Language, TranslationMap>>({
    en: {},
    ny: {},
  });

  React.useEffect(() => {
    const saved = window.localStorage.getItem("dlem_lang");
    if (saved === "ny" || saved === "en") {
      setLanguageState(saved);
    }
    fetchContentStrings()
      .then((rows) => {
        if (!Array.isArray(rows)) return;
        const next: Record<Language, TranslationMap> = { en: {}, ny: {} };
        rows.forEach((row: { key: string; english: string; chichewa: string }) => {
          next.en[row.key] = row.english;
          next.ny[row.key] = row.chichewa;
        });
        setLiveStrings(next);
      })
      .catch(() => undefined);
  }, []);

  React.useEffect(() => {
    document.documentElement.lang = language === "ny" ? "ny" : "en";
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    window.localStorage.setItem("dlem_lang", lang);
  };

  const t = (
    key: string,
    values: Record<string, string | number> = {},
  ): string => {
    const fallback = values.default ? String(values.default) : key;
    const englishTemplate = liveStrings.en[key] || translations.en[key] || fallback;
    let template =
      language === "ny"
        ? liveStrings.ny[key] || translations.ny[key] || englishTemplate
        : englishTemplate;
    Object.entries(values).forEach(([name, value]) => {
      template = template.replace(`{${name}}`, String(value));
    });
    return template;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

