"use client";
import React, { createContext, useContext, useState } from "react";
import { fetchContentStrings } from "./api";

export type Language = "en" | "ny";

type TranslationMap = Record<string, string>;

const translations: Record<Language, TranslationMap> = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.profile": "Financial Profile",
    "nav.institutions": "Check Eligibility",
    "nav.compare": "Compare Lenders",
    "nav.loans": "Active Loans",
    "nav.calculator": "Calculator",
    "nav.back": "Back",
    "nav.logout": "Sign Out",
    "theme.light": "Light Mode",
    "theme.dark": "Dark Mode",
    "prefs.label": "Display preferences",
    "prefs.language": "Language",
    "action.apply": "Compare Lenders",
    "home.welcome": "Welcome",
    "home.noBank": "No Bank",
    "home.completeProfile": "Complete your financial profile",
    "home.unlockMsg": "to unlock loan eligibility checks and applications.",
    "home.setupLink": "Set up profile",
    "home.salary": "Monthly Salary",
    "home.dti": "DTI Ratio",
    "home.activePrincipal": "Active Principal",
    "home.risk": "Risk Level",
    "home.netIncome": "Net income",
    "home.threshold": "Threshold: 33%",
    "home.remainingBalance": "Remaining balance",
    "home.riskCategory": "Risk Category",
    "home.high": "High",
    "home.moderate": "Moderate",
    "home.low": "Low",
    "home.debtAnalysis": "Debt-to-Income Analysis",
    "home.creditUtilization": "Credit Utilization",
    "home.utilizing": "Utilizing {percent}% of estimated borrowing capacity",
    "home.smartInsights": "Smart Insights",
    "home.quickActions": "Quick Actions",
    "home.recentApplications": "Recent Applications",
    "home.viewAll": "View All",
    "home.date": "Date",
    "home.amount": "Amount",
    "home.duration": "Duration",
    "home.riskScore": "Risk Score",
    "home.status": "Status",
    "home.months": "months",
    "home.insightHighRisk": "High Risk: DTI exceeds 33%. You may face rejection for new loans.",
    "home.insightModerateRisk": "Moderate Risk: DTI between 20-33%. Manageable but monitor closely.",
    "home.insightLowRisk": "Low Risk: DTI under 20%. You have healthy borrowing capacity.",
    "home.insightCapacity": "You have available capacity for additional borrowing.",
    "home.actionCheckTitle": "Check Eligibility",
    "home.actionCheckDesc": "See which institutions you qualify for",
    "home.actionCompareTitle": "Compare Lenders",
    "home.actionCompareDesc": "Side-by-side bank comparison",
    "home.actionRecordTitle": "Record Manual Loan",
    "home.actionRecordDesc": "Track your existing loans",
    "home.actionLoansTitle": "Active Loans",
    "home.actionLoansDesc": "View amortization schedules",
    "home.actionProfileTitle": "Update Profile",
    "home.actionProfileDesc": "Edit financial information",
    "eligibility.title": "Loan Eligibility Comparison",
    "eligibility.subtitle":
      "Discover where you are likely to qualify and compare terms across Malawian lenders.",
    "eligibility.profileRequired": "You need to complete your",
    "eligibility.profileLink": "financial profile",
    "eligibility.profileRequiredEnd": "before generating a comparison.",
    "eligibility.parameters": "Loan Details",
    "eligibility.amount": "Requested Amount (MK)",
    "eligibility.period": "Repayment Period",
    "eligibility.periodHelp": "Choose your comfortable repayment timeframe",
    "eligibility.months": "months",
    "eligibility.years": "years",
    "eligibility.loading": "Scanning lenders...",
    "eligibility.check": "Check Eligibility",
    "eligibility.selectInstitution": "Select Institution",
    "eligibility.chooseInstitution": "Choose an institution",
    "eligibility.compareAllLendersInfo": "All active lenders are selected by default. Uncheck ones you do not want to include.",
    "eligibility.compare": "Compare Eligible Lenders",
    "eligibility.summarySalary": "Based on your net salary of",
    "eligibility.summaryDeductions": "and existing deductions of",
    "eligibility.topMatches": "Top Eligible Matches",
    "eligibility.noMatches":
      "No lenders matched your requested amount and profile. Check the ineligible list below to see why.",
    "eligibility.bestMatch": "Best Match",
    "eligibility.interestRate": "Interest Rate",
    "eligibility.processingFee": "Processing Fee",
    "eligibility.monthlyPayment": "Est. Monthly Payment",
    "eligibility.maxCapacity": "Max Capacity",
    "eligibility.prequalified": "Pre-qualified",
    "eligibility.visitBranch": "Visit any {institution} branch to proceed.",
    "eligibility.otherInstitutions": "Other Institutions (Not Eligible)",
    "eligibility.availableLenders": "Available Lenders on DLEM",
    "eligibility.offers": "Offers {rate}% interest rates up to {months} months.",
    "check.title": "Check Eligibility",
    "check.subtitle": "Choose one lender and answer the guided questions before checking.",
    "check.loading": "Loading live institution data...",
    "check.emptyInstitutions": "No institutions are currently available. Please check back soon.",
    "check.continue": "Continue",
    "check.refresh": "Refresh",
    "check.selectInstitutionStep": "Select Institution",
    "check.subselectStep": "Select Product",
    "check.additionalDetailsStep": "Additional Details",
    "check.resultsStep": "Eligibility Results",
    "check.fincaProductTitle": "Select a FINCA Loan Product",
    "check.fincaProductDescription": "Choose the loan product you would like to check your eligibility for.",
    "check.fincaEmptyProducts": "No FINCA loan products are currently available. Please check back soon.",
    "check.fincaValidation": "Please select a loan product to continue.",
    "check.fincaMoreSoon": "More FINCA loan products will be added soon.",
    "check.comingSoon": "Coming Soon",
    "check.backToInstitutions": "Back",
    "check.productFallbackDescription": "Eligibility criteria are managed by the lender.",
    "auth.back": "Back",
    "auth.loginTitle": "Welcome Back",
    "auth.loginSubtitle": "Sign in to access your dashboard",
    "auth.email": "Email Address",
    "auth.emailPlaceholder": "your@email.com",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Your password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.signIn": "Sign In",
    "auth.signingIn": "Signing in...",
    "auth.newCustomer": "New customer?",
    "auth.createAccount": "Create an Account",
    "auth.invalidLogin": "Invalid email or password. Please try again.",
    "auth.networkError": "Network error. Please try again.",
    "auth.registerTitle": "Create Account",
    "auth.registerSubtitle": "Join thousands of Malawians managing loans digitally",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "e.g. John Banda",
    "auth.nationalId": "National ID",
    "auth.nationalIdPlaceholder": "MW-XXXXXXXXXX",
    "auth.employeeNumber": "Employee / Member ID",
    "auth.employeeNumberPlaceholder": "e.g. CS-2024-XXXX",
    "auth.phone": "Phone Number",
    "auth.phonePlaceholder": "+265 XXXXXXXX",
    "auth.emailRegisterPlaceholder": "yourname@example.com",
    "auth.emailHelp": "Your login details and notifications will be sent here.",
    "auth.validEmail": "Valid email",
    "auth.invalidEmail": "Enter a valid email address (e.g. john@example.com)",
    "auth.passwordMin": "Min. 8 characters",
    "auth.passwordTooShort": "At least 8 characters required",
    "auth.confirmPassword": "Confirm Password",
    "auth.confirmPasswordPlaceholder": "Repeat password",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordsMatch": "Passwords match",
    "auth.creatingAccount": "Creating Account...",
    "auth.createAccountButton": "Create Account",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.checkEmailTitle": "Check Your Email",
    "auth.checkEmailSubtitle": "We sent a 6-digit verification code to",
    "auth.enterAllDigits": "Please enter all 6 digits.",
    "auth.invalidOtp": "Invalid or expired code. Please try again.",
    "auth.verifyNetworkError": "Network error - could not verify your code. Please try again.",
    "auth.resendError": "Could not resend code. Please try again.",
    "auth.registrationFailed": "Registration failed. Please try again.",
    "auth.registrationNetworkError": "Network error - could not reach the server. Please check your connection.",
    "auth.developmentCode": "Development code",
    "auth.verifying": "Verifying...",
    "auth.verifyCreate": "Verify & Create Account",
    "auth.didNotReceive": "Didn't receive a code?",
    "auth.resendIn": "Resend in {seconds}s",
    "auth.resendCode": "Resend code",
    "auth.hidePassword": "Hide password",
    "auth.showPassword": "Show password",
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.save": "Save",
    "calc.title": "Loan Calculator",
    "calc.subtitle": "Caps, rates, and terms come from the live institution criteria API.",
    "calc.loading": "Loading calculator...",
    "calc.institution": "Institution",
    "calc.loanProduct": "Loan Product",
    "calc.loanAmount": "Loan Amount",
    "calc.annualInterest": "Annual Interest Rate",
    "calc.fixed": "{rate}% fixed",
    "calc.repaymentPeriod": "Repayment Period",
    "calc.monthlyInstallment": "Monthly Installment",
    "calc.totalRepayable": "Total Repayable",
    "calc.dtiCap": "DTI Cap",
    "calc.processingFee": "Processing Fee",
    "loans.title": "My Loans",
    "loans.subtitle": "Track your active loans",
    "loans.loading": "Loading loans...",
    "loans.record": "Record Manual Loan",
    "loans.active": "Active Loans",
    "loans.monthly": "Monthly",
    "loans.paidMonths": "Paid Months",
    "loans.remaining": "Remaining",
    "loans.startDate": "Start Date",
    "loans.progress": "Repayment Progress",
    "loans.viewSchedule": "View Schedule",
    "loans.manualRecord": "Manual Record",
    "loans.removeConfirm": "Are you sure you want to remove this loan? This will also update your monthly debt capacity.",
    "loans.remove": "Remove loan",
    "loans.markPaidConfirm": "Mark this whole loan as fully paid?\n\nRemaining balance: MK {balance}",
    "loans.completeError": "Could not complete loan",
    "loans.processing": "Processing...",
    "loans.markFullyPaid": "Mark Loan as Fully Paid",
    "profile.title": "Financial Profile",
    "profile.subtitle": "This information is used to calculate your loan eligibility and risk score across Malawian lenders.",
    "profile.employmentDetails": "Employment Details",
    "profile.employer": "Employer / Organization",
    "profile.employerPlaceholder": "e.g. Ministry of Health, Airtel, etc.",
    "profile.employmentCategory": "Employment Category",
    "profile.selectCategory": "Select Category",
    "profile.civilServant": "Civil Servant (Government)",
    "profile.privateSector": "Private Sector",
    "profile.selfEmployed": "Self-Employed / Business Owner",
    "profile.categoryHelp": "This determines which lenders and multipliers you are eligible for.",
    "profile.netSalary": "Net Monthly Salary (MK)",
    "profile.salaryHelp": "Enter your monthly take-home pay in Malawian Kwacha (after all standard tax deductions).",
    "profile.serviceLength": "Length of Service / Time in Business",
    "profile.monthsLabel": "(months)",
    "profile.serviceHelp": "Enter the total number of months you have been employed or in business. Used by SACCO and other lenders to verify minimum service requirements.",
    "profile.personalFinancial": "Personal & Financial Details",
    "profile.primaryBank": "Primary Salary Bank",
    "profile.unbanked": "Unbanked / Other",
    "profile.bankHelp": "Where your salary is deposited. Leave blank if unbanked.",
    "profile.age": "Age",
    "profile.housingStatus": "Housing Status",
    "profile.selectStatus": "Select status",
    "profile.owner": "Property Owner",
    "profile.tenant": "Tenant / Renting",
    "profile.family": "Living with Family",
    "profile.existingRepayments": "Monthly Existing Loan Repayments (MK)",
    "profile.existingHelp": "Total monthly repayments on all current loans. Affects your DTI ratio.",
    "profile.dependants": "Number of Dependants",
    "profile.dependantsHelp": "Total number of people financially dependent on you (children, spouse, parents, etc.).",
    "profile.bankingYears": "Years with Current Bank",
    "profile.saved": "Profile saved successfully!",
    "profile.saveFailed": "Save failed.",
    "profile.saving": "Saving...",
    "profile.saveProfile": "Save Profile",
  },
  ny: {
    "nav.dashboard": "Zoyang'anira",
    "nav.profile": "Mbiri Yachuma",
    "nav.institutions": "Onani Mwayi",
    "nav.compare": "Yerekezerani Obwereketsa",
    "nav.loans": "Ngongole Zanga",
    "nav.calculator": "Chowerengera",
    "nav.back": "Back",
    "nav.logout": "Tulukani",
    "theme.light": "Mawonekedwe Owoneka",
    "theme.dark": "Mawonekedwe Amdima",
    "prefs.label": "[NY] Display preferences",
    "prefs.language": "[NY] Language",
    "action.apply": "Yerekezerani Obwereketsa",
    "home.welcome": "Takulandirani",
    "home.noBank": "Palibe Banki",
    "home.completeProfile": "Malizitsani mbiri yanu ya zachuma",
    "home.unlockMsg": "kuti mutsegule kuyang'ana mwayi wa ngongole.",
    "home.setupLink": "Konzani mbiri",
    "home.salary": "Malipiro Apamwezi",
    "home.dti": "Chiwerengero cha Ngongole",
    "home.activePrincipal": "Ngongole Yotsala",
    "home.risk": "Mulingo wa Chiwopsezo",
    "home.netIncome": "[NY] Net income",
    "home.threshold": "[NY] Threshold: 33%",
    "home.remainingBalance": "[NY] Remaining balance",
    "home.riskCategory": "[NY] Risk Category",
    "home.high": "[NY] High",
    "home.moderate": "[NY] Moderate",
    "home.low": "[NY] Low",
    "home.debtAnalysis": "[NY] Debt-to-Income Analysis",
    "home.creditUtilization": "[NY] Credit Utilization",
    "home.utilizing": "[NY] Utilizing {percent}% of estimated borrowing capacity",
    "home.smartInsights": "[NY] Smart Insights",
    "home.quickActions": "[NY] Quick Actions",
    "home.recentApplications": "[NY] Recent Applications",
    "home.viewAll": "[NY] View All",
    "home.date": "[NY] Date",
    "home.amount": "[NY] Amount",
    "home.duration": "[NY] Duration",
    "home.riskScore": "[NY] Risk Score",
    "home.status": "[NY] Status",
    "home.months": "[NY] months",
    "home.insightHighRisk": "[NY] High Risk: DTI exceeds 33%. You may face rejection for new loans.",
    "home.insightModerateRisk": "[NY] Moderate Risk: DTI between 20-33%. Manageable but monitor closely.",
    "home.insightLowRisk": "[NY] Low Risk: DTI under 20%. You have healthy borrowing capacity.",
    "home.insightCapacity": "[NY] You have available capacity for additional borrowing.",
    "home.actionCheckTitle": "[NY] Check Eligibility",
    "home.actionCheckDesc": "[NY] See which institutions you qualify for",
    "home.actionCompareTitle": "[NY] Compare Lenders",
    "home.actionCompareDesc": "[NY] Side-by-side bank comparison",
    "home.actionRecordTitle": "[NY] Record Manual Loan",
    "home.actionRecordDesc": "[NY] Track your existing loans",
    "home.actionLoansTitle": "[NY] Active Loans",
    "home.actionLoansDesc": "[NY] View amortization schedules",
    "home.actionProfileTitle": "[NY] Update Profile",
    "home.actionProfileDesc": "[NY] Edit financial information",
    "eligibility.title": "Kuyerekeza Mwayi wa Ngongole",
    "eligibility.subtitle":
      "Onani komwe mungavomerezedwe ndipo yerekezerani mawu a obwereketsa ku Malawi.",
    "eligibility.profileRequired": "Muyenera kumaliza",
    "eligibility.profileLink": "mbiri yanu ya zachuma",
    "eligibility.profileRequiredEnd": "musanayambe kuyerekeza.",
    "eligibility.parameters": "Zambiri za Ngongole",
    "eligibility.amount": "Ndalama Zomwe Mukufuna (MK)",
    "eligibility.period": "Nthawi Yobweza",
    "eligibility.periodHelp": "Sankhani nthawi yobweza yomwe ingakuyenereni",
    "eligibility.months": "miyezi",
    "eligibility.years": "zaka",
    "eligibility.loading": "Tikuyang'ana obwereketsa...",
    "eligibility.check": "Onani Mwayi",
    "eligibility.compareAllLendersInfo": "Obwereketsa onse omwe alipo akusankhidwa mwachisawawa. Chotsani amene mukufuna osasinthidwa.",
    "eligibility.compare": "Yerekezerani Obwereketsa",
    "eligibility.selectInstitution": "Sankhani Obwereketsa",
    "eligibility.chooseInstitution": "Sankhani obwereketsa",
    "eligibility.summarySalary": "Zatengera malipiro anu a neti a",
    "eligibility.summaryDeductions": "ndi zobweza zina za",
    "eligibility.topMatches": "Obwereketsa Oyenera Kwambiri",
    "eligibility.noMatches":
      "Palibe wobwereketsa amene wagwirizana ndi ndalama zomwe mukufuna. Onani mndandanda wapansi kuti mudziwe chifukwa.",
    "eligibility.bestMatch": "Woyenera Kwambiri",
    "eligibility.interestRate": "Chiwongola Dzanja",
    "eligibility.processingFee": "Ndalama Zokonza",
    "eligibility.monthlyPayment": "Zobweza Pamwezi",
    "eligibility.maxCapacity": "Malire a Ngongole",
    "eligibility.prequalified": "Mungayenerere",
    "eligibility.visitBranch": "Pitani ku nthambi ya {institution} kuti mupitirize.",
    "eligibility.otherInstitutions": "Ena Osayenerera",
    "eligibility.availableLenders": "Obwereketsa Omwe Alipo pa DLEM",
    "eligibility.offers":
      "Amapereka chiwongola dzanja cha {rate}% mpaka miyezi {months}.",
    "check.title": "Onani Mwayi",
    "check.subtitle": "Sankhani wobwereketsa mmodzi ndipo yankhani mafunso musanayambe kuyang'ana.",
    "check.loading": "[NY] Loading live institution data...",
    "check.emptyInstitutions": "[NY] No institutions are currently available. Please check back soon.",
    "check.continue": "[NY] Continue",
    "check.refresh": "[NY] Refresh",
    "check.selectInstitutionStep": "[NY] Select Institution",
    "check.subselectStep": "[NY] Select Product",
    "check.additionalDetailsStep": "[NY] Additional Details",
    "check.resultsStep": "[NY] Eligibility Results",
    "check.fincaProductTitle": "[NY] Select a FINCA Loan Product",
    "check.fincaProductDescription": "[NY] Choose the loan product you would like to check your eligibility for.",
    "check.fincaEmptyProducts": "[NY] No FINCA loan products are currently available. Please check back soon.",
    "check.fincaValidation": "[NY] Please select a loan product to continue.",
    "check.fincaMoreSoon": "[NY] More FINCA loan products will be added soon.",
    "check.comingSoon": "[NY] Coming Soon",
    "check.backToInstitutions": "[NY] Back",
    "check.productFallbackDescription": "[NY] Eligibility criteria are managed by the lender.",
    "auth.back": "[NY] Back",
    "auth.loginTitle": "[NY] Welcome Back",
    "auth.loginSubtitle": "[NY] Sign in to access your dashboard",
    "auth.email": "[NY] Email Address",
    "auth.emailPlaceholder": "[NY] your@email.com",
    "auth.password": "[NY] Password",
    "auth.passwordPlaceholder": "[NY] Your password",
    "auth.forgotPassword": "[NY] Forgot Password?",
    "auth.signIn": "[NY] Sign In",
    "auth.signingIn": "[NY] Signing in...",
    "auth.newCustomer": "[NY] New customer?",
    "auth.createAccount": "[NY] Create an Account",
    "auth.invalidLogin": "[NY] Invalid email or password. Please try again.",
    "auth.networkError": "[NY] Network error. Please try again.",
    "auth.registerTitle": "[NY] Create Account",
    "auth.registerSubtitle": "[NY] Join thousands of Malawians managing loans digitally",
    "auth.fullName": "[NY] Full Name",
    "auth.fullNamePlaceholder": "[NY] e.g. John Banda",
    "auth.nationalId": "[NY] National ID",
    "auth.nationalIdPlaceholder": "[NY] MW-XXXXXXXXXX",
    "auth.employeeNumber": "[NY] Employee / Member ID",
    "auth.employeeNumberPlaceholder": "[NY] e.g. CS-2024-XXXX",
    "auth.phone": "[NY] Phone Number",
    "auth.phonePlaceholder": "[NY] +265 XXXXXXXX",
    "auth.emailRegisterPlaceholder": "[NY] yourname@example.com",
    "auth.emailHelp": "[NY] Your login details and notifications will be sent here.",
    "auth.validEmail": "[NY] Valid email",
    "auth.invalidEmail": "[NY] Enter a valid email address (e.g. john@example.com)",
    "auth.passwordMin": "[NY] Min. 8 characters",
    "auth.passwordTooShort": "[NY] At least 8 characters required",
    "auth.confirmPassword": "[NY] Confirm Password",
    "auth.confirmPasswordPlaceholder": "[NY] Repeat password",
    "auth.passwordMismatch": "[NY] Passwords do not match",
    "auth.passwordsMatch": "[NY] Passwords match",
    "auth.creatingAccount": "[NY] Creating Account...",
    "auth.createAccountButton": "[NY] Create Account",
    "auth.alreadyHaveAccount": "[NY] Already have an account?",
    "auth.checkEmailTitle": "[NY] Check Your Email",
    "auth.checkEmailSubtitle": "[NY] We sent a 6-digit verification code to",
    "auth.enterAllDigits": "[NY] Please enter all 6 digits.",
    "auth.invalidOtp": "[NY] Invalid or expired code. Please try again.",
    "auth.verifyNetworkError": "[NY] Network error - could not verify your code. Please try again.",
    "auth.resendError": "[NY] Could not resend code. Please try again.",
    "auth.registrationFailed": "[NY] Registration failed. Please try again.",
    "auth.registrationNetworkError": "[NY] Network error - could not reach the server. Please check your connection.",
    "auth.developmentCode": "[NY] Development code",
    "auth.verifying": "[NY] Verifying...",
    "auth.verifyCreate": "[NY] Verify & Create Account",
    "auth.didNotReceive": "[NY] Didn't receive a code?",
    "auth.resendIn": "[NY] Resend in {seconds}s",
    "auth.resendCode": "[NY] Resend code",
    "auth.hidePassword": "[NY] Hide password",
    "auth.showPassword": "[NY] Show password",
    "common.loading": "[NY] Loading...",
    "common.back": "[NY] Back",
    "common.save": "[NY] Save",
    "calc.title": "[NY] Loan Calculator",
    "calc.subtitle": "[NY] Caps, rates, and terms come from the live institution criteria API.",
    "calc.loading": "[NY] Loading calculator...",
    "calc.institution": "[NY] Institution",
    "calc.loanProduct": "[NY] Loan Product",
    "calc.loanAmount": "[NY] Loan Amount",
    "calc.annualInterest": "[NY] Annual Interest Rate",
    "calc.fixed": "[NY] {rate}% fixed",
    "calc.repaymentPeriod": "[NY] Repayment Period",
    "calc.monthlyInstallment": "[NY] Monthly Installment",
    "calc.totalRepayable": "[NY] Total Repayable",
    "calc.dtiCap": "[NY] DTI Cap",
    "calc.processingFee": "[NY] Processing Fee",
    "loans.title": "[NY] My Loans",
    "loans.subtitle": "[NY] Track your active loans",
    "loans.loading": "[NY] Loading loans...",
    "loans.record": "[NY] Record Manual Loan",
    "loans.active": "[NY] Active Loans",
    "loans.monthly": "[NY] Monthly",
    "loans.paidMonths": "[NY] Paid Months",
    "loans.remaining": "[NY] Remaining",
    "loans.startDate": "[NY] Start Date",
    "loans.progress": "[NY] Repayment Progress",
    "loans.viewSchedule": "[NY] View Schedule",
    "loans.manualRecord": "[NY] Manual Record",
    "loans.removeConfirm": "[NY] Are you sure you want to remove this loan? This will also update your monthly debt capacity.",
    "loans.remove": "[NY] Remove loan",
    "loans.markPaidConfirm": "[NY] Mark this whole loan as fully paid?\n\nRemaining balance: MK {balance}",
    "loans.completeError": "[NY] Could not complete loan",
    "loans.processing": "[NY] Processing...",
    "loans.markFullyPaid": "[NY] Mark Loan as Fully Paid",
    "profile.title": "[NY] Financial Profile",
    "profile.subtitle": "[NY] This information is used to calculate your loan eligibility and risk score across Malawian lenders.",
    "profile.employmentDetails": "[NY] Employment Details",
    "profile.employer": "[NY] Employer / Organization",
    "profile.employerPlaceholder": "[NY] e.g. Ministry of Health, Airtel, etc.",
    "profile.employmentCategory": "[NY] Employment Category",
    "profile.selectCategory": "[NY] Select Category",
    "profile.civilServant": "[NY] Civil Servant (Government)",
    "profile.privateSector": "[NY] Private Sector",
    "profile.selfEmployed": "[NY] Self-Employed / Business Owner",
    "profile.categoryHelp": "[NY] This determines which lenders and multipliers you are eligible for.",
    "profile.netSalary": "[NY] Net Monthly Salary (MK)",
    "profile.salaryHelp": "[NY] Enter your monthly take-home pay in Malawian Kwacha (after all standard tax deductions).",
    "profile.serviceLength": "[NY] Length of Service / Time in Business",
    "profile.monthsLabel": "[NY] (months)",
    "profile.serviceHelp": "[NY] Enter the total number of months you have been employed or in business. Used by SACCO and other lenders to verify minimum service requirements.",
    "profile.personalFinancial": "[NY] Personal & Financial Details",
    "profile.primaryBank": "[NY] Primary Salary Bank",
    "profile.unbanked": "[NY] Unbanked / Other",
    "profile.bankHelp": "[NY] Where your salary is deposited. Leave blank if unbanked.",
    "profile.age": "[NY] Age",
    "profile.housingStatus": "[NY] Housing Status",
    "profile.selectStatus": "[NY] Select status",
    "profile.owner": "[NY] Property Owner",
    "profile.tenant": "[NY] Tenant / Renting",
    "profile.family": "[NY] Living with Family",
    "profile.existingRepayments": "[NY] Monthly Existing Loan Repayments (MK)",
    "profile.existingHelp": "[NY] Total monthly repayments on all current loans. Affects your DTI ratio.",
    "profile.dependants": "[NY] Number of Dependants",
    "profile.dependantsHelp": "[NY] Total number of people financially dependent on you (children, spouse, parents, etc.).",
    "profile.bankingYears": "[NY] Years with Current Bank",
    "profile.saved": "[NY] Profile saved successfully!",
    "profile.saveFailed": "[NY] Save failed.",
    "profile.saving": "[NY] Saving...",
    "profile.saveProfile": "[NY] Save Profile",
  },
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: "en",
  setLanguage: () => {},
  t: key => translations.en[key] || key,
});

export const LanguageProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [language, setLanguageState] = useState<Language>("en");
  const [liveStrings, setLiveStrings] = useState<Record<Language, TranslationMap>>({
    en: {},
    ny: {},
  });

  React.useEffect(() => {
    const saved = window.localStorage.getItem("dlem_lang");
    if (saved === "ny" || saved === "en") {
      setLanguageState(saved);
    }
    fetchContentStrings()
      .then((rows) => {
        if (!Array.isArray(rows)) return;
        const next: Record<Language, TranslationMap> = { en: {}, ny: {} };
        rows.forEach((row: { key: string; english: string; chichewa: string }) => {
          next.en[row.key] = row.english;
          next.ny[row.key] = row.chichewa;
        });
        setLiveStrings(next);
      })
      .catch(() => undefined);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    window.localStorage.setItem("dlem_lang", lang);
  };

  const t = (
    key: string,
    values: Record<string, string | number> = {},
  ): string => {
    const englishTemplate = liveStrings.en[key] || translations.en[key] || key;
    let template =
      language === "ny"
        ? liveStrings.ny[key] || translations.ny[key] || `[NY] ${englishTemplate}`
        : englishTemplate;
    Object.entries(values).forEach(([name, value]) => {
      template = template.replace(`{${name}}`, String(value));
    });
    return template;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
